In [3]:
! pip install pandas

Collecting pandas
  Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bouaf\projet-data-visualisation\projetvis\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\bouaf\projet-data-visualisation\projetvis\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.1

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [8]:
data = pd.read_csv("dataset_ressources/ai_job_trends_dataset.csv", na_values=["", "None", "none", "?", "NA", "N/A", "na", "n/a", "NaN", "nan", "NULL", "null", "N.A.", "missing", "undefined", "-", "--", "...", "NaT"])

In [9]:
data.head()

,Job Title,Industry,Job Status,AI Impact Level,Median Salary (USD),Required Education,Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Location,Gender Diversity (%)
0,Investment analyst,IT,Increasing,Moderate,42109.76,Master’s Degree,5,1515,6342,55.96,28.28,UK,44.63
1,"Journalist, newspaper",Manufacturing,Increasing,Moderate,132298.57,Master’s Degree,15,1243,6205,16.81,89.71,USA,66.39
2,Financial planner,Finance,Increasing,Low,143279.19,Bachelor’s Degree,4,3338,1154,91.82,72.97,Canada,41.13
3,Legal secretary,Healthcare,Increasing,High,97576.13,Associate Degree,15,7173,4060,1.89,99.94,Australia,65.76
4,Aeronautical engineer,IT,Increasing,Low,60956.63,Master’s Degree,13,5944,7396,53.76,37.65,Germany,72.57

In [10]:
data.columns

Index(['Job Title', 'Industry', 'Job Status', 'AI Impact Level',
       'Median Salary (USD)', 'Required Education',
       'Experience Required (Years)', 'Job Openings (2024)',
       'Projected Openings (2030)', 'Remote Work Ratio (%)',
       'Automation Risk (%)', 'Location', 'Gender Diversity (%)'],
      dtype='str')

# EDA

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Job Title                    30000 non-null  str
 1   Industry                     30000 non-null  str
 2   Job Status                   30000 non-null  str
 3   AI Impact Level              30000 non-null  str
 4   Median Salary (USD)          30000 non-null  float64
 5   Required Education           30000 non-null  str
 6   Experience Required (Years)  30000 non-null  int64
 7   Job Openings (2024)          30000 non-null  int64
 8   Projected Openings (2030)    30000 non-null  int64
 9   Remote Work Ratio (%)        30000 non-null  float64
 10  Automation Risk (%)          30000 non-null  float64
 11  Location                     30000 non-null  str
 12  Gender Diversity (%)         30000 non-null  float64
dtypes: float64(4), int64(3), str(6)
memory usage: 3.0 MB

In [12]:
data.isna().sum()

Job Title                      0
Industry                       0
Job Status                     0
AI Impact Level                0
Median Salary (USD)            0
Required Education             0
Experience Required (Years)    0
Job Openings (2024)            0
Projected Openings (2030)      0
Remote Work Ratio (%)          0
Automation Risk (%)            0
Location                       0
Gender Diversity (%)           0
dtype: int64

In [17]:
for col in data :
    print(f"for the colum {col} we have {data[col].nunique()}: \n {data[col].unique()}\n")

for the colum Job Title we have 639:
 <StringArray>
[                     'Investment analyst',
                   'Journalist, newspaper',
                       'Financial planner',
                         'Legal secretary',
                   'Aeronautical engineer',
                     'Surveyor, insurance',
                                 'Dentist',
   'Emergency planning/management officer',
                     'Visual merchandiser',
                 'Housing manager/officer',
 ...
                    'Sports administrator',
                 'Therapist, occupational',
             'Lecturer, further education',
                  'Geologist, engineering',
                    'Pharmacist, hospital',
                            'Retail buyer',
          'Teaching laboratory technician',
                    'Optician, dispensing',
                  'Engineer, agricultural',
 'Diplomatic Services operational officer']
Length: 639, dtype: str

for the colum Industry we have 8:
 <StringArray>
[            'IT',  'Manufacturing',        'Finance',     'Healthcare',
      'Education',  'Entertainment',         'Retail', 'Transportation']
Length: 8, dtype: str

for the colum Job Status we have 2:
 <StringArray>
['Increasing', 'Decreasing']
Length: 2, dtype: str

for the colum AI Impact Level we have 3:
 <StringArray>
['Moderate', 'Low', 'High']
Length: 3, dtype: str

for the colum Median Salary (USD) we have 29968:
 [ 42109.76 132298.57 143279.19 ...  97305.51  95599.22  65679.61]

for the colum Required Education we have 5:
 <StringArray>
[  'Master’s Degree', 'Bachelor’s Degree',  'Associate Degree',
       'High School',               'PhD']
Length: 5, dtype: str

for the colum Experience Required (Years) we have 21:
 [ 5 15  4 13 20  7  0 12 16 17  2  3 11  8 14  1 18  9  6 10 19]

for the colum Job Openings (2024) we have 9439:
 [1515 1243 3338 ... 7415 6411 5884]

for the colum Projected Openings (2030) we have 9410:
 [6342 6205 1154 ... 9180 7245 2833]

for the colum Remote Work Ratio (%) we have 9466:
 [55.96 16.81 91.82 ... 25.88 95.76 93.15]

for the colum Automation Risk (%) we have 9519:
 [28.28 89.71 72.97 ... 32.44 71.59 89.82]

for the colum Location we have 8:
 <StringArray>
['UK', 'USA', 'Canada', 'Australia', 'Germany', 'China', 'India', 'Brazil']
Length: 8, dtype: str

for the colum Gender Diversity (%) we have 5965:
 [44.63 66.39 41.13 ... 38.12 55.88 37.92]

In [18]:
data.duplicated().sum()

np.int64(0)

In [19]:
data.describe()

,Median Salary (USD),Experience Required (Years),Job Openings (2024),Projected Openings (2030),Remote Work Ratio (%),Automation Risk (%),Gender Diversity (%)
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,90119.965639,10.051433,5039.640833,5074.218100,49.836431,50.154229,49.979660
std,34412.013953,6.060678,2861.009654,2866.550722,28.966688,28.754889,17.274665
min,30001.860000,0.000000,100.000000,100.000000,0.000000,0.000000,20.000000
25%,60500.702500,5.000000,2570.000000,2586.750000,24.570000,25.400000,35.070000
50%,90274.115000,10.000000,5034.000000,5106.500000,49.570000,50.020000,49.885000
75%,119454.710000,15.000000,7527.000000,7573.000000,75.100000,75.030000,64.910000
max,149998.500000,20.000000,10000.000000,10000.000000,100.000000,99.990000,80.000000